(ns com.phronemophobic.clj-libretro.constants
  (:refer-clojure :exclude [name]))

(def RETRO_ENVIRONMENT_EXPERIMENTAL 0x10000)

(def constants
  ((fn [m]
     (update-vals m int))
   {:RETRO_ENVIRONMENT_SET_ROTATION  1  
    :RETRO_ENVIRONMENT_GET_OVERSCAN  2  
    :RETRO_ENVIRONMENT_GET_CAN_DUPE  3  
    :RETRO_ENVIRONMENT_SET_MESSAGE   6  
    :RETRO_ENVIRONMENT_SHUTDOWN      7  
    :RETRO_ENVIRONMENT_SET_PERFORMANCE_LEVEL 8
    :RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY 9
    :RETRO_ENVIRONMENT_SET_PIXEL_FORMAT 10
    :RETRO_ENVIRONMENT_SET_INPUT_DESCRIPTORS 11
    :RETRO_ENVIRONMENT_SET_KEYBOARD_CALLBACK 12
    :RETRO_ENVIRONMENT_SET_DISK_CONTROL_INTERFACE 13
    :RETRO_ENVIRONMENT_SET_HW_RENDER 14
    :RETRO_ENVIRONMENT_GET_VARIABLE 15
    :RETRO_ENVIRONMENT_SET_VARIABLES 16
    :RETRO_ENVIRONMENT_GET_VARIABLE_UPDATE 17
    :RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME 18
    :RETRO_ENVIRONMENT_GET_LIBRETRO_PATH 19
    :RETRO_ENVIRONMENT_SET_FRAME_TIME_CALLBACK 21
    :RETRO_ENVIRONMENT_SET_AUDIO_CALLBACK 22
    :RETRO_ENVIRONMENT_GET_RUMBLE_INTERFACE 23
    :RETRO_ENVIRONMENT_GET_INPUT_DEVICE_CAPABILITIES 24
    :RETRO_ENVIRONMENT_GET_SENSOR_INTERFACE (bit-or 25  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_CAMERA_INTERFACE (bit-or 26  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_LOG_INTERFACE 27
    :RETRO_ENVIRONMENT_GET_PERF_INTERFACE 28
    :RETRO_ENVIRONMENT_GET_LOCATION_INTERFACE 29
    :RETRO_ENVIRONMENT_GET_CONTENT_DIRECTORY 30 
    :RETRO_ENVIRONMENT_GET_CORE_ASSETS_DIRECTORY 30
    :RETRO_ENVIRONMENT_GET_SAVE_DIRECTORY 31
    :RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO 32
    :RETRO_ENVIRONMENT_SET_PROC_ADDRESS_CALLBACK 33
    :RETRO_ENVIRONMENT_SET_SUBSYSTEM_INFO 34
    :RETRO_ENVIRONMENT_SET_CONTROLLER_INFO 35
    :RETRO_ENVIRONMENT_SET_MEMORY_MAPS (bit-or 36  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_SET_GEOMETRY 37
    :RETRO_ENVIRONMENT_GET_USERNAME 38
    :RETRO_ENVIRONMENT_GET_LANGUAGE 39
    :RETRO_ENVIRONMENT_GET_CURRENT_SOFTWARE_FRAMEBUFFER (bit-or 40  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_HW_RENDER_INTERFACE (bit-or 41  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS (bit-or 42  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE (bit-or 43  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_SET_SERIALIZATION_QUIRKS 44
    :RETRO_ENVIRONMENT_SET_HW_SHARED_CONTEXT (bit-or 44  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_VFS_INTERFACE (bit-or 45  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_LED_INTERFACE (bit-or 46  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_AUDIO_VIDEO_ENABLE (bit-or 47  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_MIDI_INTERFACE (bit-or 48  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_FASTFORWARDING (bit-or 49  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_TARGET_REFRESH_RATE (bit-or 50  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_INPUT_BITMASKS (bit-or 51  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_CORE_OPTIONS_VERSION 52
    :RETRO_ENVIRONMENT_SET_CORE_OPTIONS 53
    :RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL 54
    :RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY 55
    :RETRO_ENVIRONMENT_GET_PREFERRED_HW_RENDER 56
    :RETRO_ENVIRONMENT_GET_DISK_CONTROL_INTERFACE_VERSION 57
    :RETRO_ENVIRONMENT_SET_DISK_CONTROL_EXT_INTERFACE 58
    :RETRO_ENVIRONMENT_GET_MESSAGE_INTERFACE_VERSION 59
    :RETRO_ENVIRONMENT_SET_MESSAGE_EXT 60
    :RETRO_ENVIRONMENT_GET_INPUT_MAX_USERS 61
    :RETRO_ENVIRONMENT_SET_AUDIO_BUFFER_STATUS_CALLBACK 62
    :RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY 63
    :RETRO_ENVIRONMENT_SET_FASTFORWARDING_OVERRIDE 64
    :RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE 65
    :RETRO_ENVIRONMENT_GET_GAME_INFO_EXT 66
    :RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2 67
    :RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL 68
    :RETRO_ENVIRONMENT_SET_CORE_OPTIONS_UPDATE_DISPLAY_CALLBACK 69
    :RETRO_ENVIRONMENT_SET_VARIABLE 70
    :RETRO_ENVIRONMENT_GET_THROTTLE_STATE (bit-or 71  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_SAVESTATE_CONTEXT (bit-or 72  RETRO_ENVIRONMENT_EXPERIMENTAL)
    :RETRO_ENVIRONMENT_GET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE_SUPPORT (bit-or 73  RETRO_ENVIRONMENT_EXPERIMENTAL)


    ;; /* Regular save RAM. This RAM is usually found on a game cartridge,
    ;; * backed up by a battery.
    ;; * If save game data is too complex for a single memory buffer,
    ;; * the SAVE_DIRECTORY (preferably) or SYSTEM_DIRECTORY environment
    ;; * callback can be used. */
    :RETRO_MEMORY_SAVE_RAM    0

    ;; /* Some games have a built-in clock to keep track of time.
    ;; * This memory is usually just a couple of bytes to keep track of time.
    ;; */
    :RETRO_MEMORY_RTC         1

    ;; /* System ram lets a frontend peek into a game systems main RAM. */
    :RETRO_MEMORY_SYSTEM_RAM  2

    ;; /* Video ram lets a frontend peek into a game systems video RAM (VRAM). */
    :RETRO_MEMORY_VIDEO_RAM   3

    }))

(def device-ids-
  {:RETRO_DEVICE_ID_JOYPAD_B        0
   :RETRO_DEVICE_ID_JOYPAD_Y        1
   :RETRO_DEVICE_ID_JOYPAD_SELECT   2
   :RETRO_DEVICE_ID_JOYPAD_START    3
   :RETRO_DEVICE_ID_JOYPAD_UP       4
   :RETRO_DEVICE_ID_JOYPAD_DOWN     5
   :RETRO_DEVICE_ID_JOYPAD_LEFT     6
   :RETRO_DEVICE_ID_JOYPAD_RIGHT    7
   :RETRO_DEVICE_ID_JOYPAD_A        8
   :RETRO_DEVICE_ID_JOYPAD_X        9
   :RETRO_DEVICE_ID_JOYPAD_L       10
   :RETRO_DEVICE_ID_JOYPAD_R       11
   :RETRO_DEVICE_ID_JOYPAD_L2      12
   :RETRO_DEVICE_ID_JOYPAD_R2      13
   :RETRO_DEVICE_ID_JOYPAD_L3      14
   :RETRO_DEVICE_ID_JOYPAD_R3      15})
(def constants'
  (into {}
        (map (fn [[k v]]
               [v k]))
        constants))

(defn name [i]
  (get constants' i))


(def device-ids
  ((fn [m]
     (update-vals m int))
   {:RETRO_DEVICE_ID_JOYPAD_B        0
    :RETRO_DEVICE_ID_JOYPAD_Y        1
    :RETRO_DEVICE_ID_JOYPAD_SELECT   2
    :RETRO_DEVICE_ID_JOYPAD_START    3
    :RETRO_DEVICE_ID_JOYPAD_UP       4
    :RETRO_DEVICE_ID_JOYPAD_DOWN     5
    :RETRO_DEVICE_ID_JOYPAD_LEFT     6
    :RETRO_DEVICE_ID_JOYPAD_RIGHT    7
    :RETRO_DEVICE_ID_JOYPAD_A        8
    :RETRO_DEVICE_ID_JOYPAD_X        9
    :RETRO_DEVICE_ID_JOYPAD_L       10
    :RETRO_DEVICE_ID_JOYPAD_R       11
    :RETRO_DEVICE_ID_JOYPAD_L2      12
    :RETRO_DEVICE_ID_JOYPAD_R2      13
    :RETRO_DEVICE_ID_JOYPAD_L3      14
    :RETRO_DEVICE_ID_JOYPAD_R3      15}))
(def device-ids'
  (into {}
        (map (fn [[k v]]
               [v k]))
        device-ids))
(defn device-name [id]
  (get device-ids' id))
